//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAdmin
    {
        public int Admin_ID { get; set; }
        public int Role_ID { get; set; }
        public string Admin_Alias { get; set; }
        public string Admin_Name { get; set; }
        public string Admin_Password { get; set; }
        public bool Is_Delete { get; set; }
    
        public virtual tbRole tbRole { get; set; }
    }
}
