//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBonusConfig
    {
        public int Category_ID { get; set; }
        public int Balance_Num { get; set; }
        public int JSNum { get; set; }
        public System.DateTime Create_Time { get; set; }
        public double TuiJian_Para1 { get; set; }
        public double CenJiang_Para1 { get; set; }
        public double CenJiang_Para2 { get; set; }
        public double CenJiang_Para3 { get; set; }
        public double JianDian_Para1 { get; set; }
        public int JianDian_Para2 { get; set; }
        public double ZiJianGuanLi_Para1 { get; set; }
        public double ZiJianGuanLi_Para2 { get; set; }
        public double ZiJianGuanLi_Para3 { get; set; }
        public double ZiJianGuanLi_Para4 { get; set; }
        public double ZiJianGuanLi_Para5 { get; set; }
        public double DianBu_Para1 { get; set; }
        public double FengHong_Para1 { get; set; }
        public double FengHong_Para2 { get; set; }
        public double CeJiang_Para1 { get; set; }
        public double CeJiang_Para2 { get; set; }
        public double FangJiang_Para1 { get; set; }
        public double FangJiang_Para2 { get; set; }
        public double LYou_Para1 { get; set; }
        public double LYou_Para2 { get; set; }
        public double FuXiao_Para1 { get; set; }
        public double FuXiao_Para2 { get; set; }
        public double FuXiao_Para3 { get; set; }
        public double FuXiao_Para4 { get; set; }
        public double XianDai_Para1 { get; set; }
        public double SiDai_Para1 { get; set; }
        public double SenDai_Para1 { get; set; }
        public double Tax_Para1 { get; set; }
    }
}
