//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMemberAccount
    {
        public int Member_ID { get; set; }
        public double Sum_Bonus { get; set; }
        public double Sum_ECurrency { get; set; }
        public double Sum_FuXiao { get; set; }
        public double Left_Bonus { get; set; }
        public double Left_ECurrency { get; set; }
        public double Left_FuXiao { get; set; }
        public System.DateTime Update_Time { get; set; }
    
        public virtual tbMemberInfo tbMemberInfo { get; set; }
    }
}
