//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMessage
    {
        public int Message_ID { get; set; }
        public int Sender_ID { get; set; }
        public string Sender_Type { get; set; }
        public System.DateTime Send_Time { get; set; }
        public int Receiver_ID { get; set; }
        public int Receiver_Type { get; set; }
        public string Message_Send { get; set; }
        public string Message_Reply { get; set; }
        public System.DateTime Reply_Time { get; set; }
        public bool State { get; set; }
    }
}
