//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMemberInfo
    {
        public tbMemberInfo()
        {
            this.tbBonusRecord = new HashSet<tbBonusRecord>();
            this.tbMemberAccountChangeRecord = new HashSet<tbMemberAccountChangeRecord>();
            this.tbMemberBonusTotal = new HashSet<tbMemberBonusTotal>();
            this.tbMemberUpgradeRecord = new HashSet<tbMemberUpgradeRecord>();
        }
    
        public int Member_ID { get; set; }
        public int P_ID { get; set; }
        public int R_ID { get; set; }
        public int Qu { get; set; }
        public int P_IDs { get; set; }
        public int R_IDs { get; set; }
        public int P_Depth { get; set; }
        public int R_Depth { get; set; }
        public int Depth_FilledAll { get; set; }
        public int P_ChildNum { get; set; }
        public int Left_Seven { get; set; }
        public int Right_Seven { get; set; }
        public int P_Sum_ThreeLayer { get; set; }
        public int R_ChildNum { get; set; }
        public double A_Sum_History { get; set; }
        public double A_Sum_Add { get; set; }
        public double A_Sum_Nocash { get; set; }
        public int A_Member_Count { get; set; }
        public double B_Sum_History { get; set; }
        public double B_Sum_Add { get; set; }
        public double B_Sum_Nocash { get; set; }
        public int B_Member_Count { get; set; }
        public double R_Sum_History { get; set; }
        public double R_Sum_Add { get; set; }
        public int R_Member_Count { get; set; }
        public double P_Sum_FuxXiao { get; set; }
        public double P_Current_FuXiao { get; set; }
        public double BenRen_Sum_FuXiao { get; set; }
        public double BenRen_Current_FuXiao { get; set; }
        public double BenRen_BenYue_FuXiao { get; set; }
        public double P_Sum_Retail { get; set; }
        public double P_Current_Retail { get; set; }
        public double BenRen_Sum_Retail { get; set; }
        public double BenRen_Current_Retail { get; set; }
        public string Member_Name { get; set; }
        public string Member_Alias { get; set; }
        public string Member_RealName { get; set; }
        public string First_Password { get; set; }
        public string Second_Password { get; set; }
        public bool Sex { get; set; }
        public string Phone { get; set; }
        public string Bank_Account { get; set; }
        public string Open_Bank { get; set; }
        public int Address_ID { get; set; }
        public string DetailAddress { get; set; }
        public int Manager_Level { get; set; }
        public int AllyGrade_ID { get; set; }
        public System.DateTime Register_Time { get; set; }
        public int registrant_ID { get; set; }
        public int registrant_Type { get; set; }
        public bool Is_Empty { get; set; }
        public bool Is_Cancelled { get; set; }
        public bool Is_Delete { get; set; }
        public double First_Money { get; set; }
        public double First_PV { get; set; }
        public double Real_Money { get; set; }
        public double Real_PV { get; set; }
        public double Sum_Money { get; set; }
        public double Sum_PV { get; set; }
        public int Balance_Num { get; set; }
        public int SCenter_ID { get; set; }
        public bool Is_Send { get; set; }
        public bool Is_Balanced { get; set; }
    
        public virtual tbAllyGrade tbAllyGrade { get; set; }
        public virtual ICollection<tbBonusRecord> tbBonusRecord { get; set; }
        public virtual tbMemberAccount tbMemberAccount { get; set; }
        public virtual ICollection<tbMemberAccountChangeRecord> tbMemberAccountChangeRecord { get; set; }
        public virtual ICollection<tbMemberBonusTotal> tbMemberBonusTotal { get; set; }
        public virtual tbSCenterInfo tbSCenterInfo { get; set; }
        public virtual ICollection<tbMemberUpgradeRecord> tbMemberUpgradeRecord { get; set; }
    }
}
