//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMemberBonusTotal
    {
        public int ID { get; set; }
        public int Member_ID { get; set; }
        public int Balance_Num { get; set; }
        public double Sum_TuiJian { get; set; }
        public double Current_TuiJian { get; set; }
        public double Sum_CenJiang { get; set; }
        public double Current_CenJiang { get; set; }
        public double Sum_JianDian { get; set; }
        public double Current_JianDian { get; set; }
        public double Sum_ZiJianGuanLi { get; set; }
        public double Current_ZiJianGuanLi { get; set; }
        public double Sum_DianBu { get; set; }
        public double Current_DianBu { get; set; }
        public double Sum_FenHong { get; set; }
        public double Current_FenHong { get; set; }
        public double Sum_CeJiang { get; set; }
        public double Current_CeJiang { get; set; }
        public double Sum_FangJiang { get; set; }
        public double Current_FangJiang { get; set; }
        public double Sum_Lyou { get; set; }
        public double Current_Lyou { get; set; }
        public double Sum_DaiLiJiang { get; set; }
        public double Current_DaiLiJiang { get; set; }
        public double Sum_LinSou { get; set; }
        public double Current_LinSou { get; set; }
        public double Sum_FuXiao { get; set; }
        public double Current_FuXiao { get; set; }
        public double Sum_Tax { get; set; }
        public double Current_Tax { get; set; }
        public double Sum_Total { get; set; }
        public double Current_Total { get; set; }
        public System.DateTime Update_Time { get; set; }
        public bool Is_Released { get; set; }
        public System.DateTime Released_Time { get; set; }
        public bool Is_Cancelled { get; set; }
        public System.DateTime Cancelled_Time { get; set; }
    
        public virtual tbMemberInfo tbMemberInfo { get; set; }
    }
}
