//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMemberUpgradeRecord
    {
        public int Record_ID { get; set; }
        public int Member_ID { get; set; }
        public int OldAllyGrade_ID { get; set; }
        public int NewAllyGrade_ID { get; set; }
        public double Money { get; set; }
        public double PV { get; set; }
        public int Operator_ID { get; set; }
        public System.DateTime Operate_Time { get; set; }
    
        public virtual tbMemberInfo tbMemberInfo { get; set; }
    }
}
