//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNews
    {
        public int News_ID { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Editor { get; set; }
        public System.DateTime Release_Time { get; set; }
        public int Releaser_ID { get; set; }
        public int Receiver_Type { get; set; }
        public bool Is_Delete { get; set; }
        public System.DateTime Delete_Time { get; set; }
    }
}
