//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduct
    {
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Alias { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public double PV { get; set; }
        public string Product_Code { get; set; }
        public int Product_Tag { get; set; }
        public int Stocked_Num { get; set; }
        public int SalesVolume { get; set; }
        public int SendedVolume { get; set; }
        public bool Is_Delete { get; set; }
    }
}
