//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRole
    {
        public tbRole()
        {
            this.tbAdmin = new HashSet<tbAdmin>();
            this.tbRoleMenu = new HashSet<tbRoleMenu>();
        }
    
        public int Role_ID { get; set; }
        public string Role_Name { get; set; }
        public bool Is_Delete { get; set; }
        public bool Is_Hide { get; set; }
    
        public virtual ICollection<tbAdmin> tbAdmin { get; set; }
        public virtual ICollection<tbRoleMenu> tbRoleMenu { get; set; }
    }
}
