//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSCenterInfo
    {
        public tbSCenterInfo()
        {
            this.tbMemberInfo = new HashSet<tbMemberInfo>();
            this.tbSCenterAccountChangeRecord = new HashSet<tbSCenterAccountChangeRecord>();
        }
    
        public int SCenter_ID { get; set; }
        public string SCenter_Name { get; set; }
        public string ServinceCenter_RealName { get; set; }
        public string First_Password { get; set; }
        public string Second_Password { get; set; }
        public int Scenter_Level { get; set; }
        public int Address_ID { get; set; }
        public string DetailAddress { get; set; }
        public bool Is_Delete { get; set; }
        public int SCenterManager_ID { get; set; }
        public string SCenterManager_Name { get; set; }
        public string SCenterManager_Phone { get; set; }
    
        public virtual ICollection<tbMemberInfo> tbMemberInfo { get; set; }
        public virtual tbSCenterAccount tbSCenterAccount { get; set; }
        public virtual ICollection<tbSCenterAccountChangeRecord> tbSCenterAccountChangeRecord { get; set; }
    }
}
