//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbShoppingRecord
    {
        public int Record_ID { get; set; }
        public string Order_ID { get; set; }
        public int Product_ID { get; set; }
        public string Customer_ID { get; set; }
        public int Customer_Type { get; set; }
        public System.DateTime Buy_Time { get; set; }
        public string Product_Name { get; set; }
        public int Buy_Count { get; set; }
        public double Sum_Price { get; set; }
        public double Sum_PV { get; set; }
        public string Receiver_Name { get; set; }
        public string Receiver_Address { get; set; }
        public string Receiver_Phone { get; set; }
        public string Description { get; set; }
        public System.DateTime Send_Time { get; set; }
        public int Operator_ID { get; set; }
        public string Express_Info { get; set; }
    }
}
