//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMember
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbTiderEntities : DbContext
    {
        public dbTiderEntities()
            : base("name=dbTiderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbAdmin> tbAdmin { get; set; }
        public DbSet<tbAllyGrade> tbAllyGrade { get; set; }
        public DbSet<tbBonusConfig> tbBonusConfig { get; set; }
        public DbSet<tbBonusRecord> tbBonusRecord { get; set; }
        public DbSet<tbCart> tbCart { get; set; }
        public DbSet<tbCity> tbCity { get; set; }
        public DbSet<tbDataBaseState> tbDataBaseState { get; set; }
        public DbSet<tbJmail> tbJmail { get; set; }
        public DbSet<tbMemberAccount> tbMemberAccount { get; set; }
        public DbSet<tbMemberAccountChangeRecord> tbMemberAccountChangeRecord { get; set; }
        public DbSet<tbMemberBonusTotal> tbMemberBonusTotal { get; set; }
        public DbSet<tbMemberInfo> tbMemberInfo { get; set; }
        public DbSet<tbMemberUpgradeRecord> tbMemberUpgradeRecord { get; set; }
        public DbSet<tbMessage> tbMessage { get; set; }
        public DbSet<tbNews> tbNews { get; set; }
        public DbSet<tbProduct> tbProduct { get; set; }
        public DbSet<tbProvince> tbProvince { get; set; }
        public DbSet<tbRole> tbRole { get; set; }
        public DbSet<tbRoleMenu> tbRoleMenu { get; set; }
        public DbSet<tbSCenterAccount> tbSCenterAccount { get; set; }
        public DbSet<tbSCenterAccountChangeRecord> tbSCenterAccountChangeRecord { get; set; }
        public DbSet<tbSCenterInfo> tbSCenterInfo { get; set; }
        public DbSet<tbShoppingRecord> tbShoppingRecord { get; set; }
        public DbSet<tbWithdrawRules> tbWithdrawRules { get; set; }
    }
}
